#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          pyload
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the pyload.
# Description:       Enable service provided by pyload.
### END INIT INFO

NAME=pyload
DAEMON=/opt/pyload/pyLoadCore.py
USER=pyload
STOP_TIMEOUT=30
PIDFILE=/var/run/$NAME.pid

export PATH="${PATH:+$PATH:}/sbin"

[ -x $DAEMON ] || exit 0

[ -e /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

start_daemon () {
    if [ $ENABLE_DAEMON != 1 ]; then
        log_progress_msg "(disabled)"
		log_end_msg 255 || true
    else    
        start-stop-daemon --start --pidfile $PIDFILE \
        --chuid $USER --exec $DAEMON \
        -- --daemon $OPTIONS | cut -d" " -f 3 > $PIDFILE
		log_end_msg 0
    fi
}

case "$1" in
    start)
        log_daemon_msg "Starting daemon" "$NAME"
        start_daemon
        ;;
    stop)
        log_daemon_msg "Stopping daemon" "$NAME"
        start-stop-daemon --stop --quiet \
            --retry $STOP_TIMEOUT --pidfile $PIDFILE
        log_end_msg 0
        ;;
    restart)
        log_daemon_msg "Restarting daemon" "$NAME"
        start-stop-daemon --stop --quiet \
            --retry $STOP_TIMEOUT --pidfile $PIDFILE
        start_daemon
        ;;
    *)
        log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart}" || true
        exit 2
        ;;
esac

exit 0

