#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          syncthing
# Required-Start:    $syslog $local_fs $network $remote_fs
# Required-Stop:     $syslog $local_fs $network $remote_fs
# Should-Start:      $remote_fs $named
# Should-Stop:       $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop syncthing daemon.
# Description:       Enable service provided by syncthing.
### END INIT INFO

NAME=syncthing
DAEMON=/usr/bin/$NAME
USER=syncthing
STOP_TIMEOUT=30

export PATH="${PATH:+$PATH:}/sbin"

[ -x $DAEMON ] || exit 0

[ -e /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

if [ $ENABLE_DAEMON != 1 ]; then
    log_progress_msg "(disabled)"
    log_end_msg 255 || true
    exit 0
fi

start_daemon() {
    start-stop-daemon --start --chuid $USER --background \
     --exec $DAEMON -- $OPTIONS || { log_end_msg $?; exit 1; }
}

stop_daemon() {
    start-stop-daemon --stop --quiet --retry $STOP_TIMEOUT \
     --exec $DAEMON --oknodo || { log_end_msg $?; exit 1; }
}

case "$1" in
    start)
        log_daemon_msg "Starting daemon" "$NAME" && log_end_msg 0
        start_daemon
        ;;
    stop)
        log_daemon_msg "Stopping daemon" "$NAME" && log_end_msg 0
        stop_daemon
        ;;
    restart)
        log_daemon_msg "Restarting daemon" "$NAME" && log_end_msg 0
        stop_daemon
        sleep 1
        start_daemon
        ;;
    *)
        log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart}" || true
        exit 2
        ;;
esac

exit 0

