#!/bin/bash
# Run by smartd daemon.
# It notifies the user of the failure by mail, wall and led.
# --------------------------------
# cyruz - http://ciroprincipe.info

# Import common functions.
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common/nas_common.sh" || exit 1

# Check...
preliminary_check

# Turn on fail led.
toggle_led fail

# Notify by mail.
mail_notify "$SMARTD_FAILTYPE" "$SMARTD_MESSAGE"

# Notify user. COMMENTED, NOT WORKING.
#echo "$SMARTD_MESSAGE" | wall

exit 0
