#!/bin/bash
# This script helps cron deciding the order of NAS related jobs.
# It must be executed one time per day by crontab:
# 0 4 * * * root /oopt/thecus/nas_cron_helper >/dev/null 2>&1
# --------------------------------
# cyruz - http://ciroprincipe.info

# Scripts.
S1="/opt/thecus/nas_dropbox_sync"
S2="/opt/thecus/nas_backup"
S3="/opt/thecus/nas_snapraid"
S4="/opt/thecus/nas_snapraid scrub"

# Weekdays script chains.
MON="$S1; $S3"
TUE="$S1; $S3"
WED="$S2"
THU="$S1; $S3"
FRI="$S1; $S3"
SAT="$S2"
SUN="$S4"

# Check if running as root.
[[ $(id -u) -ne 0 ]] && { echo "Please run this script as root."; exit 1; }

# Get current weekday and execute script chain using indirect expansion.
DAY=$(date +%a | tr [:lower:] [:upper:])
${!DAY}
