#!/bin/bash
# This script shuts down or reboots the NAS.
# It checks if important operations are going on before doing it.
# --------------------------------
# cyruz - http://ciroprincipe.info

# Import common functions.
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common/nas_common.sh" || exit 1

# Checks...
preliminary_check

# Check parameters.
[[ "$1" != "shutdown" && "$1" != "reboot" ]] && { echo "Usage: nas_sysdown <shutdown | reboot>"; exit 1; }

# Check if any sync or backup script is running.
# If it is, try to terminate it gracefully and sleep for 10 seconds.
[[ -f $LOCK_FILE ]] && { kill -SIGTERM $(< $LOCK_FILE); sleep 10s; }

# Shutdown or reboot.
[[ "$1" == "shutdown" ]] && PARAM="-h" || PARAM="-r"
/sbin/shutdown $PARAM -t 0 now
